services:
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
      target: builder
    command: npm run start:dev auth
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres


  notifications:
    build:
      context: .
      dockerfile: apps/notifications/Dockerfile
      target: builder
    command: npm run start:dev notifications
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    depends_on:
      - postgres


  search:
    build:
      context: .
      dockerfile: apps/search/Dockerfile
      target: builder
    command: npm run start:dev search
    ports:
      - "3002:3002"
    volumes:
      - .:/app
    env_file:
      - ./apps/search/.env
    depends_on:
      - postgres


  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: merz_search_db
    ports:
      - 5432:5432