services:
  auth-app:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
      target: builder
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - "4000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres


  # notifications:
  #   build:
  #     context: .
  #     dockerfile: apps/notifications/Dockerfile
  #     target: builder
  #   command: npm run start:dev notifications
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - postgres


  search-app:
    build:
      context: .
      dockerfile: apps/search/Dockerfile
      target: builder
    command: npm run start:dev search
    ports:
      - "3020:3020"
      - "3021:3021"
    volumes:
      - .:/app
    env_file:
      - ./apps/search/.env
    depends_on:
      - postgres


  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: merz_search_db
    ports:
      - 5432:5432