name: Node.js CI
run-name: ${{ github.actor }} is building artifacts 🚀

on:
  push:
    branches:
      - dev

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    environment: dev

    # strategy:
    #   matrix:
    #     node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Verify environment variables
        run: |
          echo "docker build -t ${{ secrets.IMAGE }}:${{ env.TAG }}  -f apps/admin/Dockerfile ."

      # build docker images
      # Build the Docker image
      - name: Build artifacts
        run: |-
          docker build -t gcr.io/${{ secrets.GKE_PROJECT }}/${{ env.IMAGE }}:$GITHUB_SHA -f apps/admin/Dockerfile .

      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE }}:$GITHUB_SHA

      # Optionally, tag the image as 'latest' and push
      - name: Tag and push latest image
        run: |
          docker tag gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE }}:$GITHUB_SHA gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE }}:latest
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE }}:latest

# docker  build -t europe-west3-docker.pkg.dev/merz-medical-forum/admin/dev:0.0.1 -f apps/admin/Dockerfile .
# docker push europe-west3-docker.pkg.dev/merz-medical-forum/admin/dev:0.0.1
