name: Node.js CI
run-name: ${{ github.actor }} is building the medical-forum app 🚀

on:
  push:
    branches:
      - dev

jobs:
  install_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      # Set up pnpm
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      # Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # Install dependencies
      # echo step
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Run build if present
      - name: Build admin project
        run: pnpm run build admin

      # Run tests for search app
      - name: Run unit tests for admin
        run: pnpm run test admin
